version: 2

sources:
  - name: raw
    database: "{{ env_var('DATA_DB_NAME') }}"
    schema: raw

    tables:
      - name: weather_snapshots

        config:
          loaded_at_field: ingested_at

          freshness:
            warn_after:
              count: 2
              period: hour

            error_after:
              count: 4
              period: hour